version: '3'
services:
    grafana:
        env_file: configuration.env
        ports:
            - '3000:3000'
        volumes:
            - grafana_data:/var/lib/grafana
            - ./grafana/provisioning/:/etc/grafana/provisioning/
            - ./grafana/dashboards/:/etc/grafana/dashboards/
        environment:
            - GF_DATE_FORMATS_DEFAULT_TIMEZONE=browser
            - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/dashboards/Home.json
        container_name: grafana
        image: grafana/grafana
        depends_on:
            - influxdb
        restart: unless-stopped
    influxdb:
        volumes:
            - influxdb_data:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=telegraf
        container_name: influxdb
        image: influxdb:1.8
        restart: unless-stopped
    telegraf:
        build: ./telegraf
        env_file: configuration.env
        volumes:
            - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
        container_name: telegraf
        depends_on:
            - influxdb
        restart: unless-stopped
volumes:
    grafana_data: {}
    influxdb_data: {}
